#!/usr/bin/env python

import sys
import readline
import rlcompleter
readline.parse_and_bind("tab: complete")

from rflib import *



intro = """'RfCat, the greatest thing since Frequency Hopping!'

Don't you wish this were a CLI!?  Sorry.  Maybe soon...
For now, enjoy the raw power of rflib, or write your own device-specific CLI!

currently your environment has an object called "d" for dongle.  this is how 
you interact with the rfcat dongle, for :
    >>> d.ping()
    >>> d.setFreq(433000000)
    >>> d.setMdmModulation(MOD_ASK_OOK)
    >>> d.makePktFLEN(250)
    >>> d.RFxmit("HALLO")
    >>> d.RFrecv()
    >>> print d.reprRadioConfig()

"""

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('-r', '--research', default=False, action="store_true", help='Interactive Python and the "d" instance to talk to your dongle.  melikey longtime.')
    parser.add_argument('-i', '--index', default=0, type=int) 

    ifo = parser.parse_args()

    if ifo.research:
        interactive(ifo.index, DongleClass=RfCat, intro=intro)

    else:
        # do the full-rfcat thing
        d = RfCat(ifo.index)
        d.rf_configure(**ifo.__dict__)
        d.rf_redirection((sys.stdin, sys.stdout))

